### ISSUE TITLE
README.MD instruction section has a typo that affects installation "requirments.txt" should read "requirements.txt"

### ISSUE THREAD

**Issue by lithoso** [Nourepide/ComfyUI-Allore#1]
README.MD instruction section has a typo that affects installation:

pip install -r requirments.txt <----

pip install -r requirments.txt
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirments.txt'

corrected name  should read "requirements.txt"

**Comment by Nourepide** [comment]
Thank you, the typo has just been fixed.
